const plantData = [
  {
    commonName: 'Monstera, \'Swiss Cheese Plant\'',
    scientificName: 'Monstera deliciosa',
    imageUrl: 'https://images.unsplash.com/photo-1625582598943-2445bb7b8253?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1035&q=80',
    description: 'Monstera deliciosa, also known as the Swiss cheese plant, is a popular houseplant native to the tropical rainforests of Central and South America. It is loved for its unique, large, glossy leaves with natural holes, or fenestrations.',
    careGuide: "**Monstera deliciosa**, also known as the Swiss cheese plant, is a popular houseplant native to the tropical rainforests of Central and South America. It is loved for its unique, large, glossy leaves with natural holes, or fenestrations. Here are the detailed care instructions for Monstera deliciosa:\n\n- **Light:** Monstera deliciosa prefers bright, indirect light. They can tolerate lower light conditions, but their growth may slow and the characteristic fenestrations may not develop as well. In terms of foot candles (fc), an appropriate range would be 200-1000 fc. Remember that too much direct sunlight can cause the leaves to burn.\n\n- **Water:** These plants prefer their soil to dry out slightly between waterings. A good rule of thumb is to water when the top inch or so of the soil feels dry. The exact frequency of watering will depend on the plant's environment, such as light, humidity, and temperature conditions, but generally, watering every 1-2 weeks is sufficient.\n\n- **Temperature:** Monstera deliciosa prefers temperatures between 65-85°F (18-29°C). They can tolerate slightly lower temperatures, but growth may slow. They are not frost tolerant.\n\n- **Humidity:** As tropical plants, they appreciate higher humidity levels, around 60-80%. However, they can adapt to typical indoor humidity levels.\n\n- **Soil:** Use a well-draining potting mix. You can make your own by mixing one part indoor potting soil, one part peat, and one part perlite or coarse sand. The pH should be between 5.5 and 7.0.\n\n- **Fertilizer:** Fertilize every 4-6 weeks during the growing season (spring and summer) with a balanced houseplant fertilizer diluted to half strength. Reduce fertilization during the winter months when the plant's growth slows.\n\n- **Pruning:** Prune as needed to control the plant's size and shape. You can also use a moss pole or other support to encourage the plant's natural climbing behavior.\n\n- **Repotting:** Repot every 2-3 years as the plant grows, or when the roots have filled the pot. Spring is the best time to repot.\n\n\nBelow is a table summarizing these care instructions:\n| Care Factor | Recommended Conditions |\n| --- | --- |\n| Light | 200-1000 fc, bright indirect light |\n| Water | When top inch of soil is dry, approx. every 1-2 weeks |\n| Temperature | 65-85°F (18-29°C) |\n| Humidity | 60-80% preferred, but can adapt to typical indoor levels |\n| Soil | Well-draining mix, pH 5.5-7.0 |\n| Fertilizer | Balanced houseplant fertilizer, every 4-6 weeks during growing season |\n| Pruning | As needed to control size and shape |\n| Repotting | Every 2-3 years, or when roots fill pot |\n\nRemember, the best care is attentive care. Keep an eye on your Monstera deliciosa's health by observing changes in its leaves and growth patterns. This can help you adjust care practices as necessary to meet the plant's needs."
  }
];

export default plantData;
